### ISSUE TITLE
provide move anchors paths other than circle/rectangle

### ISSUE THREAD

**Issue by mjy** [SpeciesFileGroup/svg-detailer#2]
when I draw a polyline, polygon, etc
    then I can not move it as a whole to a new position

**Comment by jrflood** [comment]
That is currently true . . The functionality is easy to implement given an isolation of the whole element vs point selection.

In order to de-glitch the extant functions, I deferred thinking to hard about this obvious extension.

Circles, ellipses, rectangles, and text have natural “origins” this make it simple to use them as object translators.

Possibly using the “shift” key in conjunction with the mousedown-move (drag) event would be a natural-seeming paradigm.

Rich

**Comment by jrflood** [comment]
This was done in conjunction with issue #1 in the period from 26SEP2019 -12DEC2019
